### ISSUE TITLE
Subtle differences in OPUS file metadata and array parsing

### ISSUE THREAD

**Issue by dylanbeaudette** [pierreroudier/opusreader#22]
Both of these files appear "normal" in the Bruker software, but reading them in via `opus_read()` places the "AB" or `spec` array into the `sc_ref` position. Both files are from a VERTEX 70-MIR.

![image](https://user-images.githubusercontent.com/624277/139344863-d4540534-0450-4fb8-ac4e-f5e1c0d8b6e9.png)

[examples.zip](https://github.com/pierreroudier/opusreader/files/7437677/examples.zip)

**Comment by philipp-baumann** [comment]
The issue is pending for quite some time, but finally there should be a rescue; you can checkout this, it's still WIP but we'll add a bunch of unit tests etc. You should be able to parse with the devel version on the main branch. https://github.com/spectral-cockpit/opusreader2 . If you find anything surprising, i.e. not corresponding to the Bruker OPUS viewer, pls make an issue there. Cheers

**Comment by dylanbeaudette** [comment]
Thanks! I just pulled the latest version of `opusreader` (opusreader_0.4.2) and have the same issue. I just emailed Pierre the offending example .0 files.

**Comment by dylanbeaudette** [comment]
Tried opusreader2 and all of our files are processed successfully. Moving focus to opusreader2. Thanks!
