### ISSUE TITLE
installing using remotes command doesn't work as-is

### ISSUE THREAD

**Issue by trmillertr** [pierreroudier/opusreader#25]
In order for me to install using remotes, I had to use the following command:
remotes::install_github("pierreroudier/opusreader@main")

**Comment by philipp-baumann** [comment]
I can't reproduce this issue, for me it worked without adding @main)
https://remotes.r-lib.org/reference/install_github.html
according to the documentation `ref` arg points to HEAD, i.e. the default branch on github. maybe you need a `force = TRUE`. What version of remotes are you using?

**Comment by trmillertr** [comment]
Version 2.0.4 according to 'conda list'

**Comment by philipp-baumann** [comment]
I see. According to the changelog (since remotes v2.2.0:

https://github.com/r-lib/remotes/blob/main/NEWS.md

"install_*() family of functions now use the default branch in the repository, not the master branch (@MyKo101,#508)."

We use main but no master branch because it avoids the old-fashioned connotation ;) 

As remotes is now at 2.4.2 I think it's not necessary to change. I can however note that it pulls from main branch if this is helpful.

Also if you are keen on testing a now almost universal reader: feel free to check out : github.com/spectral-cockpit/opusreader2 

Cheers
